config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :users
  root 'home#index'
  
  get 'about_us' => "home#about_us"
  get 'contact_us' => "home#contact_us"

  resources :projects
  resources :developers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/developer.rb
class Developer < ApplicationRecord
	validates :name, :role, presence: true
	validates :email, presence: true, uniqueness: true
end

app/models/project.rb
class Project < ApplicationRecord
   validates :name, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!

end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
  before_action :set_developer, only: %i[ show edit update destroy ]

  # GET /developers or /developers.json
  def index
    @developers = Developer.all
  end

  # GET /developers/1 or /developers/1.json
  def show
  end

  # GET /developers/new
  def new
    @developer = Developer.new
  end

  # GET /developers/1/edit
  def edit
  end

  # POST /developers or /developers.json
  def create
    @developer = Developer.new(developer_params)

    respond_to do |format|
      if @developer.save
        format.html { redirect_to @developer, notice: "Developer was successfully created." }
        format.json { render :show, status: :created, location: @developer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @developer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /developers/1 or /developers/1.json
  def update
    respond_to do |format|
      if @developer.update(developer_params)
        format.html { redirect_to @developer, notice: "Developer was successfully updated." }
        format.json { render :show, status: :ok, location: @developer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @developer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /developers/1 or /developers/1.json
  def destroy
    @developer.destroy
    respond_to do |format|
      format.html { redirect_to developers_url, notice: "Developer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_developer
      @developer = Developer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def developer_params
      params.require(:developer).permit(:name, :email, :role)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

def index	
end

def About_us
	
end

def contact
	
end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
   before_action :set_project, only: %i[show edit update destroy]

  def index
    @projects = Project.all
  end

  def show
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
    redirect_to project_path(@project)
    else
      render :new
      #render 'new' can also be used like this
    end  
  end

  def edit

  end

  def update
    if @project.update(project_params)
       redirect_to project_path(@project)
    else
    render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_path
    
  end


   private

   def set_project
     @project = Project.find(params[:id])
   end

   def project_params
       params.require(:project).permit(:name)
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/views/developers/_form.html.erb
<%= form_with(model: developer, local: true) do |form| %>
  <% if developer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(developer.errors.count, "error") %> prohibited this developer from being saved:</h2>

      <ul>
        <% developer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-3">
    <%= form.label :name, class: "mb-3" %>
    <%= form.text_field :name, class:"form-control form-control-lg" %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :email, class: "mb-3" %>
    <%= form.text_field :email, class:"form-control form-control-lg" %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :role, class: "mb-3" %>
    <%= form.text_field :role, class:"form-control form-control-lg" %>
  </div>

  <div class="form-group mb-3">
    <%= form.submit class:"btn btn-primary btn-lg mt-3" %>
     <%= link_to 'Back', developers_path, class:"btn btn-outline-primary btn-lg mt-3" %>
  </div>
<% end %>

app/views/developers/edit.html.erb
<div class="row">
	<div class="col-md-12 col-lg-12">
		<div class="card shadow mt-5 mb-5">
			<div class="card-body">
				<h1>Editing Developer</h1>
			    <%= render 'form', developer: @developer %>
			</div>
		</div>
	</div>
</div>

app/views/developers/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
<div class="col-md-12 col-lg-12 mt-3 mb-3">
  <h1 class="text text-dark"><strong>Developers:</strong></h1>
  <%= link_to 'New Developer', new_developer_path, class:"btn btn-primary btn-lg mb-3" %><table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Role</th>
      <th colspan="3"></th>
    </tr>
  </thead>
    <tbody>
      <% @developers.each do |developer| %>
        <tr>
            <td><%= developer.name %></td>
            <td><%= developer.email %></td>
            <td><%= developer.role %></td>
          <td>
            <div class="dropdown">
              <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                Actions
              </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
              <li><%= link_to 'Show', developer,class:"dropdown-item" %></li>
              <li><%= link_to 'Edit', edit_developer_path(developer), class:"dropdown-item" %></li>
              <li><%= link_to 'Destroy', developer, method: :delete, data: { confirm: 'Are you sure?' }, class: "dropdown-item" %></li>
            </ul>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/developers/new.html.erb
<div class="row">
	<div class="col-md-12 col-lg-12">
		<div class="card shadow mt-5 mb-5">
			<div class="card-body">
				<h1>New Developer</h1>
			    <%= render 'form', developer: @developer %>
			</div>
		</div>
	</div>
</div>

app/views/developers/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-12 col-lg-12">
    <div class="card shadow">
      <div class="card-body">
        <h1>Developers Details</h1>
        <p class="Lead">
          <strong>Name:</strong>
          <%= @developer.name %>
        </p>
        <p class="Lead">
          <strong>Email:</strong>
          <%= @developer.email %>
        </p>
        <p class="Lead">
          <strong>Role:</strong>
          <%= @developer.role %>
        </p>
          <%= link_to 'Back to list', developers_path, class: "btn btn-primary btn-lg" %>
      </div>
    </div>  
  </div>
</div>

app/views/home/about_us.html.erb
<h1>About</h1>



<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>

<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>

<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>

<p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>

<%= link_to 'Home', root_path %>

<%= link_to 'Contact Us', "/contact_us" %>

app/views/home/contact_us.html.erb
  <h1>contact</h1>
<%= link_to 'Home', "/" %>

<%= link_to 'About Us', "/about_us" %>

app/views/home/index.html.erb
<div class="row">
  <div class="col-lg-8 mx-lg-auto">
	<div class="card shadow mt-5 mb-5">
	  <div class="card-body">
		<h1>Hello world</h1>

	  <h4 class="mt-3, mb-4">Welcome to project-management app</h4>
	  <p class="Lead">
	  	It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).	
	  </p>

	  <p class="Lead">
	  	It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).	
	  </p>
    <%= link_to 'About Us', about_us_path,class:'btn btn-primary btn-lg' %>
	  <%= link_to 'Contact Us', contact_us_path,class:'btn btn-primary btn-lg'%>
	  </div>
	</div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectManagement</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <%= render 'shared/header' %>
    <% end %>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
    <% if user_signed_in? %>
      <%= render 'shared/footer' %>
    <% end %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project) do|form| %>
  <div class="form-group">
  	<%= form.label :name, class:'mb-2'%>
  	<%= form.text_field :name, class: "form-control form-control-lg" %>
    <% project.errors.full_messages_for(:name).each do|message| %>
    <p style="color:red;"><%= message %></p>
    <% end %>
  </div>

  <div class="form-group, mt-3">
   	<%= form.submit class:"btn btn-primary btn-lg" %>
    <%= link_to 'Back', projects_path, class:'btn btn-outline-primary btn-lg' %>
  </div>

 <% end %>

app/views/projects/edit.html.erb
<div class="row">
 <div class="col-md-12 col-lg-12">
    <div class="card shadow mt-5 mb-5">
	    <div class="card-body">
        <h1>Edit Project</h1>

        <%= render 'form', project: @project %>

        <%#= render partial:'form', locals:(project: @project) %>
	    </div>	
    </div>
  </div>
</div>

app/views/projects/index.html.erb
<div class="row">
  <div class="col-md-12 col-lg-12 mt-3">
    <h1 class="text text-dark"><strong>Projects:</strong></h1>
    <%= link_to 'New Project', new_project_path,class:'btn btn-primary mb-3' %>

    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Name</th>
          <th colspan="3">Actions</th>
        </tr>
      </thead> 
      <tbody>
        <% @projects.each do |project| %>
          <tr>
            <td><%= project.name %></td>
            <td>
              <%= link_to 'show', project, class:'btn btn-primary' %>
              <%= link_to 'Edit', edit_project_path(project), class:'btn btn-warning'%>
              <%= link_to 'Delete', project, method: :delete, data: {confirm:'Are you sure you want to delete this Project?'}, class:'btn btn-danger' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/projects/new.html.erb
<div class="row">
 <div class="col-md-12 col-lg-12">
    <div class="card shadow mt-5 mb-5">
	    <div class="card-body">
        <h1>New Project</h1>

        <%= render 'form', project: @project %>

        <%#= render partial:'form', locals:(project: @project) %>
	    </div>	
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<div class="row">
 <div class="col-md-12 col-lg-12">
    <div class="card shadow mt-5 mb-5">
	    <div class="card-body">
        <h1>Project Details</h1>
				<p class="Lead"><strong>Name:</strong><%= @project.name %></p>

				<%= link_to 'Back to list', projects_path , class:"btn btn-primary btn-lg" %>
	    </div>	
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="bg-primary mt-5">
	<div class="container mt-5">
		<div class="row mt-5">
			<div class="col-lg-4">
			<h1>Project Management</h1>	
			</div>
			<div class="col-lg-4">
				2021
			</div>
			<div class="col-lg-4">	
				<p class="Lead">@Appsimpact Academy </p>
			</div>	
		</div>
	</div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <%= link_to 'Project Management', root_path,class:'navbar-brand'%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', root_path,class:'nav-link active'%>
        </li>
        <li class="nav-item">
          <%= link_to 'Projects', projects_path,class:'nav-link active'%>
        </li>
          <li class="nav-item">
          <%= link_to 'Developers', developers_path,class:'nav-link active'%>
        </li>
        <% if user_signed_in? %>
            <li class="nav-item">
                <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
       <!--  <#% else %>
            <li class="nav-item">
                <#%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
                <#%= link_to 'Register', new_user_registration_path, class: 'nav-link' %>
            </li> -->
        <% end %>
      </ul>
    </div>
  </div>
</nav>